name: Publish Package

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  prepare:
    permissions:
      contents: read
    name: Prepare the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Node.js environment
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: lts/*
          cache: npm

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create tarball
        run: npm pack

      - name: Save tarball
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        with:
          name: package
          path: "*.tgz"
          retention-days: 1

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Set commit status to PENDING
        uses: myrotvorets/set-commit-status-action@5b39333f62641d4fe9c0967572f738a4aea8a15b # renovate: tag=1.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Publish to npm
          sha: ${{ github.sha }}

      - name: Set up Node.js environment
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          registry-url: https://registry.npmjs.org/

      - name: Download tarball
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: package

      - name: Publish package
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@5b39333f62641d4fe9c0967572f738a4aea8a15b # renovate: tag=1.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Publish to npm
          sha: ${{ github.sha }}
        if: always()
