name: Publish Package

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  prepare:
    permissions:
      contents: read
    name: Prepare the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Node.js environment
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: lts/*
          cache: npm

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create tarball
        run: npm pack

      - name: Save tarball
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        with:
          name: package
          path: "*.tgz"
          retention-days: 1

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Set commit status to PENDING
        uses: myrotvorets/set-commit-status-action@5b39333f62641d4fe9c0967572f738a4aea8a15b # renovate: tag=1.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Publish to npm
          sha: ${{ github.sha }}

      - name: Set up Node.js environment
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          registry-url: https://registry.npmjs.org/

      - name: Download tarball
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # renovate: tag=v2
        with:
          name: package

      - name: Publish package
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@5b39333f62641d4fe9c0967572f738a4aea8a15b # renovate: tag=1.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Publish to npm
          sha: ${{ github.sha }}
        if: always()
